import { AppData } from "./types";

export const appData: AppData = {
  sampleUser: {
    address: "0x1234...abcd",
    creditScore: 420,
    totalChallenges: 15,
    streakDays: 7,
    totalPointsEarned: 300,
    isRegistered: true,
  },
  challenges: [
    {
      type: "daily_save",
      name: "Daily Saver",
      description: "Save at least $5 today",
      points: 10,
      creditImpact: 5,
      category: "daily",
      icon: "💰",
    },
    {
      type: "bill_early",
      name: "Early Bird",
      description: "Pay a bill 3+ days early",
      points: 20,
      creditImpact: 10,
      category: "daily",
      icon: "⚡",
    },
    {
      type: "budget_check",
      name: "Budget Tracker",
      description: "Review and update your budget",
      points: 15,
      creditImpact: 8,
      category: "daily",
      icon: "📊",
    },
    {
      type: "weekly_goal",
      name: "Weekly Saver",
      description: "Save $50+ this week",
      points: 50,
      creditImpact: 25,
      category: "weekly",
      icon: "🎯",
    },
  ],
  achievements: [
    {
      id: "first_challenge",
      name: "First Steps",
      description: "Complete your first challenge",
      icon: "🏆",
      unlocked: true,
    },
    {
      id: "week_streak",
      name: "Week Warrior",
      description: "Maintain a 7-day streak",
      icon: "🔥",
      unlocked: true,
    },
    {
      id: "month_streak",
      name: "Monthly Master",
      description: "Maintain a 30-day streak",
      icon: "💎",
      unlocked: false,
    },
    {
      id: "good_credit",
      name: "Good Credit Club",
      description: "Reach 650 credit score",
      icon: "⭐",
      unlocked: false,
    },
    {
      id: "savings_master",
      name: "Savings Master",
      description: "Complete 10 savings challenges",
      icon: "🏅",
      unlocked: false,
    },
    {
      id: "perfect_score",
      name: "Perfect Credit",
      description: "Reach 850 credit score",
      icon: "👑",
      unlocked: false,
    },
  ],
  walletProviders: [
    {
      name: "MetaMask",
      id: "injected",
      icon: "🦊",
      description: "Most popular Ethereum wallet",
      downloadUrl: "https://metamask.io",
    },
    {
      name: "Coinbase Wallet",
      id: "baseAccount",
      icon: "🔵",
      description: "User-friendly wallet by Coinbase",
      downloadUrl: "https://wallet.coinbase.com",
    },
    {
      name: "WalletConnect",
      id: "walletConnect",
      icon: "🔗",
      description: "Connect with mobile wallets",
      downloadUrl: "https://walletconnect.com",
    },
    {
      name: "Sub Wallet",
      id: "app.subwallet",
      icon: "🦀",
      description: "Multi-chain wallet for Polkadot",
      downloadUrl: "https://subwallet.app",
    }
  ],
  creditcoinNetwork: {
    chainId: "0x18E9F",
    chainIdDecimal: 102031,
    chainName: "Creditcoin Testnet",
    rpcUrl: "https://rpc.cc3-testnet.creditcoin.network",
    blockExplorer: "https://creditcoin-testnet.blockscout.com",
    nativeCurrency: { name: "Creditcoin", symbol: "CTC", decimals: 18 },
  },
  contractAddress: "0x1234567890123456789012345678901234567890",
  educationalContent: [
    {
      id: "credit_basics",
      title: "Credit Score Basics",
      description: "Learn what affects your credit score",
      duration: "5 min",
      points: 25,
    },
    {
      id: "budgeting_101",
      title: "Budgeting 101",
      description: "Create your first budget",
      duration: "10 min",
      points: 35,
    },
    {
      id: "debt_management",
      title: "Debt Management",
      description: "Strategies to pay off debt faster",
      duration: "8 min",
      points: 30,
    },
    {
      id: "investment_basics",
      title: "Investment Fundamentals",
      description: "Start building wealth with smart investments",
      duration: "12 min",
      points: 40,
    },
  ],
};
