import { AppData } from "./types";

export const appData: AppData = {
  sampleUser: {
    walletAddress: "0x1234...abcd",
    creditScore: 420,
    totalChallenges: 15,
    streakDays: 7,
    bestStreak: 14,
    totalPoints: 300,
    isRegistered: true,
  },
  fanClubs: [
    {
      id: 1,
      kolName: "Crypto Titan",
      kolVerified: true,
      kolSubtitle: "DeFi Trading",
      title: "Titan's DeFi Mastery Club",
      description:
        "Learn advanced DeFi strategies from a seasoned crypto investor with 5+ years experience.",
      members: 2847,
      challenges: 12,
      avgEarnings: 850,
      socials: {
        twitter: 125000,
        youtube: 89000,
        telegram: 45000,
      },
      priceLabel: "100 MOCA",
      image: "/images/fanclubs/titan-defi.png",
      isJoined: true,
    },
    {
      id: 2,
      kolName: "NFT Sensei",
      kolVerified: false,
      kolSubtitle: "NFT Collecting",
      title: "NFT Alpha Hunters",
      description:
        "Daily NFT flips, rarity analysis, and alpha calls from experienced collectors.",
      members: 1520,
      challenges: 8,
      avgEarnings: 640,
      socials: {
        twitter: 72000,
        youtube: 23000,
        telegram: 15000,
      },
      priceLabel: "80 MOCA",
      image: "/images/fanclubs/nft-sensei.png",
      isJoined: false,
    },
    {
      id: 3,
      kolName: "Yield Farmer X",
      kolVerified: true,
      kolSubtitle: "Liquidity Mining",
      title: "Farm to Earn Collective",
      description:
        "Join hands-on yield farming missions and auto-compounding strategies.",
      members: 4110,
      challenges: 15,
      avgEarnings: 1230,
      socials: {
        twitter: 98000,
        youtube: 56000,
        telegram: 32000,
      },
      priceLabel: "150 MOCA",
      image: "/images/fanclubs/yield-farmer-x.png",
      isJoined: true,
    },
  ],
  challenges: [
    {
      id: 1,
      type: "daily_save",
      name: "Daily Saver",
      description: "Save at least $5 today",
      points: 10,
      creditImpact: 5,
      category: "daily",
      icon: "💰",
      estimatedTimeMinutes: 5,
      isCompleted: false,
    },
    {
      id: 2,
      type: "bill_early",
      name: "Early Bird",
      description: "Pay a bill 3+ days early",
      points: 20,
      creditImpact: 10,
      category: "daily",
      icon: "⚡",
      isCompleted: false,
    },
    {
      id: 3,
      type: "budget_check",
      name: "Budget Tracker",
      description: "Review and update your budget",
      points: 15,
      creditImpact: 8,
      category: "daily",
      icon: "📊",
      isCompleted: true,
    },
    {
      id: 4,
      type: "weekly_goal",
      name: "Weekly Saver",
      description: "Save $50+ this week",
      points: 50,
      creditImpact: 25,
      category: "weekly",
      icon: "🎯",
      isCompleted: false,
    },
  ],
  achievements: [
    {
      id: "first_challenge",
      name: "First Steps",
      description: "Complete your first challenge",
      icon: "🏆",
      unlocked: true,
    },
    {
      id: "week_streak",
      name: "Week Warrior",
      description: "Maintain a 7-day streak",
      icon: "🔥",
      unlocked: true,
    },
    {
      id: "month_streak",
      name: "Monthly Master",
      description: "Maintain a 30-day streak",
      icon: "💎",
      unlocked: false,
    },
    {
      id: "good_credit",
      name: "Good Credit Club",
      description: "Reach 650 credit score",
      icon: "⭐",
      unlocked: false,
    },
    {
      id: "savings_master",
      name: "Savings Master",
      description: "Complete 10 savings challenges",
      icon: "🏅",
      unlocked: false,
    },
    {
      id: "perfect_score",
      name: "Perfect Credit",
      description: "Reach 850 credit score",
      icon: "👑",
      unlocked: false,
    },
  ],
  walletProviders: [
    {
      name: "MetaMask",
      id: "io.metamask",
      icon: "🦊",
      description: "Most popular Ethereum wallet",
      downloadUrl: "https://metamask.io",
    },
    {
      name: "Coinbase Wallet",
      id: "baseAccount",
      icon: "🔵",
      description: "User-friendly wallet by Coinbase",
      downloadUrl: "https://wallet.coinbase.com",
    },
    {
      name: "WalletConnect",
      id: "walletConnect",
      icon: "🔗",
      description: "Connect with mobile wallets",
      downloadUrl: "https://walletconnect.com",
    },
    {
      name: "Sub Wallet",
      id: "app.subwallet",
      icon: "🦀",
      description: "Multi-chain wallet for Polkadot",
      downloadUrl: "https://subwallet.app",
    },
  ],
  creditcoinNetwork: {
    chainId: "0x18E9F",
    chainIdDecimal: 102031,
    chainName: "Creditcoin Testnet",
    rpcUrl: "https://rpc.cc3-testnet.creditcoin.network",
    blockExplorer: "https://creditcoin-testnet.blockscout.com",
    nativeCurrency: { name: "Creditcoin", symbol: "CTC", decimals: 18 },
  },
  contractAddress: "0x1234567890123456789012345678901234567890",
  educationalContent: [
    {
      id: "credit_basics",
      title: "Credit Score Basics",
      description: "Learn what affects your credit score",
      duration: "5 min",
      points: 25,
      isCompleted: false,
    },
    {
      id: "budgeting_101",
      title: "Budgeting 101",
      description: "Create your first budget",
      duration: "10 min",
      points: 35,
      isCompleted: true,
    },
    {
      id: "debt_management",
      title: "Debt Management",
      description: "Strategies to pay off debt faster",
      duration: "8 min",
      points: 30,
      isCompleted: false,
    },
    {
      id: "investment_basics",
      title: "Investment Fundamentals",
      description: "Start building wealth with smart investments",
      duration: "12 min",
      points: 40,
      isCompleted: false,
    },
  ],
};
