services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditgame8bit
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d creditgame8bit"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/creditgame8bit?schema=public
      NODE_ENV: production
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
